name: Publish to PyPI

on:
  release:
    types: [published] # This workflow runs when a new release is published on GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a Python version compatible with your package

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build sdist and wheel
      run: python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      env:
        # Use the secret you created in GitHub Settings -> Secrets -> Actions
        TWINE_USERNAME: __token__ # This is a special username for API tokens
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
