name: Security Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Changed to a specific version for robustness

      - name: Install dpncy with its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[demo]"

      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        # No 'with:' section initially, if you don't need to pass inputs
